apiVersion: v1
kind: Service
metadata:
  name: {{ include "speedtest-exporter.fullname" . }}
  labels:
    {{- include "speedtest-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
      appProtocol: http
  selector:
    {{- include "speedtest-exporter.selectorLabels" . | nindent 4 }}
