{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "speedtest-exporter.fullname" . }}
  labels:
    {{- include "speedtest-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: metrics
    scheme: http
  selector:
    matchLabels:
      {{- include "speedtest-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
