{
 "title": "Speedtest",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(speedtest_run_total,name)"
    }
   },
   { "name": "summary_period", "label": "Summary Period", "query": "24h" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Idle Ping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(speedtest_ping_latency_seconds{name=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(speedtest_packet_loss{name=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internet Service Provider (ISP)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_isp_info{name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_isp_info{name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface is VPN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_vpn_status{name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Sucessful Run",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_last_run_timestamp{name=\"$name\",status=\"succeeded\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bandwidth{name=\"$name\"} * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Bandwidth History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bandwidth{name=\"$name\"} * 8",
     "legendFormat": "Bandwidth"
    }
   ]
  },
  {
   "title": "Upload (Mbps)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bandwidth{name=\"$name\"} * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Bandwidth History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_upload_bandwidth{name=\"$name\"} * 8",
     "legendFormat": "Bandwidth"
    }
   ]
  },
  {
   "title": "Idle Ping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Idle Ping",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(speedtest_ping_latency_seconds{name=\"$name\"})",
       "legendFormat": "Average"
      },
      {
       "expr": "max(speedtest_ping_low_seconds{name=\"$name\"})",
       "legendFormat": "Low"
      },
      {
       "expr": "max(speedtest_ping_high_seconds{name=\"$name\"})",
       "legendFormat": "High"
      },
      {
       "expr": "max(speedtest_ping_latency_seconds{name=\"$name\"})",
       "legendFormat": "lower_fill"
      }
     ]
    },
    {
     "title": "Idle Ping Jitter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "speedtest_ping_jitter_seconds{name=\"$name\"}",
       "legendFormat": "Ping Jitter"
      }
     ]
    }
   ]
  },
  {
   "title": "Download",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downloaded Bytes [last $summary_period]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(speedtest_download_bytes{name=\"$name\"}[$summary_period]) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Download Bytes per Test [last $summary_period]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(speedtest_download_bytes{name=\"$name\"}[$summary_period])) / \r\nsum(increase(speedtest_run_total{name=\"$name\",status=\"succeeded\"}[$summary_period]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Download Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "speedtest_download_bandwidth{name=\"$name\"} * 8",
       "legendFormat": "Download Bandwidth"
      }
     ]
    },
    {
     "title": "Download Ping",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(speedtest_download_latency_iqm_seconds{name=\"$name\"}) by (name)",
       "legendFormat": "Average"
      },
      {
       "expr": "max(speedtest_download_latency_low_seconds{name=\"$name\"}) by (name)",
       "legendFormat": "Low"
      },
      {
       "expr": "max(speedtest_download_latency_high_seconds{name=\"$name\"}) by (name)",
       "legendFormat": "High"
      },
      {
       "expr": "max(speedtest_download_latency_iqm_seconds{name=\"$name\"}) by (name)",
       "legendFormat": "lower_fill"
      }
     ]
    },
    {
     "title": "Download Ping Jitter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "speedtest_download_latency_jitter_seconds{name=\"$name\"}",
       "legendFormat": "Ping Jitter"
      }
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uploaded Bytes [last $summary_period]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(speedtest_upload_bytes{name=\"$name\"}[24h]) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Upload Bytes per Test [last $summary_period]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(speedtest_upload_bytes{name=\"$name\"}[$summary_period])) / \r\nsum(increase(speedtest_run_total{name=\"$name\",status=\"succeeded\"}[$summary_period]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upload Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "speedtest_upload_bandwidth{name=\"$name\"} * 8",
       "legendFormat": "Download Bandwidth"
      }
     ]
    },
    {
     "title": "Upload Ping",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "speedtest_upload_latency_iqm_seconds{name=\"$name\"}",
       "legendFormat": "Average"
      },
      {
       "expr": "speedtest_upload_latency_low_seconds{name=\"$name\"}",
       "legendFormat": "Low"
      },
      {
       "expr": "speedtest_upload_latency_high_seconds{name=\"$name\"}",
       "legendFormat": "High"
      },
      {
       "expr": "speedtest_upload_latency_iqm_seconds{name=\"$name\"}",
       "legendFormat": "lower_fill"
      }
     ]
    },
    {
     "title": "Upload Ping Jitter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "speedtest_upload_latency_jitter_seconds{name=\"$name\"}",
       "legendFormat": "Ping Jitter"
      }
     ]
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packet Loss",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "speedtest_packet_loss{name=\"$name\"}",
       "legendFormat": "packet loss"
      }
     ]
    }
   ]
  },
  { "title": "Test Runs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Speedtest Runs by Status [last $summary_period]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(speedtest_run_total{name=\"$name\"}[$summary_period])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Test Servers",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count(speedtest_server_info{name=\"$name\"}) by (country,location,host,server_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Sucessful Run",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(speedtest_last_run_timestamp{name=\"$name\",status=\"succeeded\"} * 1000) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Failed Run",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(speedtest_last_run_timestamp{name=\"$name\",status=\"failed\"} * 1000) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Sucessful Speed Test Run Duration [last $summary_period]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(speedtest_run_duration_seconds_sum{name=\"$name\"}[$summary_period])) / \r\nsum(rate(speedtest_run_duration_seconds_count{name=\"$name\"}[$summary_period]))",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Successful Test Run Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(speedtest_run_duration_seconds_sum{name=\"$name\",status=\"succeeded\"}[$__rate_interval])) /\r\nsum(increase(speedtest_run_duration_seconds_count{name=\"$name\",status=\"succeeded\"}[$__rate_interval]))",
     "legendFormat": "Speedtest Duration"
    }
   ]
  },
  {
   "title": "Successful Test Run Durations Histogram",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(speedtest_run_duration_seconds_bucket{name=\"$name\"}[$summary_period])) by (le))",
     "legendFormat": "count"
    }
   ]
  }
 ]
}